//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACT_ELECTRONICA_PDF_XML.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteXML", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class ComprobanteXML : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosXMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosXML {
            get {
                return this.DatosXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosXMLField, value) != true)) {
                    this.DatosXMLField = value;
                    this.RaisePropertyChanged("DatosXML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AdvertenciasValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI", ItemName="AdvertenciaValidacion")]
    [System.SerializableAttribute()]
    public class AdvertenciasValidacion : System.Collections.Generic.List<FACT_ELECTRONICA_PDF_XML.ServiceReference1.AdvertenciaValidacion> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvertenciaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class AdvertenciaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NodoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SugerenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nodo {
            get {
                return this.NodoField;
            }
            set {
                if ((object.ReferenceEquals(this.NodoField, value) != true)) {
                    this.NodoField = value;
                    this.RaisePropertyChanged("Nodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Antecedente {
            get {
                return this.AntecedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteField, value) != true)) {
                    this.AntecedenteField = value;
                    this.RaisePropertyChanged("Antecedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Sugerencia {
            get {
                return this.SugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SugerenciaField, value) != true)) {
                    this.SugerenciaField = value;
                    this.RaisePropertyChanged("Sugerencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaSesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SugerenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Nodo {
            get {
                return this.NodoField;
            }
            set {
                if ((object.ReferenceEquals(this.NodoField, value) != true)) {
                    this.NodoField = value;
                    this.RaisePropertyChanged("Nodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Antecedente {
            get {
                return this.AntecedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteField, value) != true)) {
                    this.AntecedenteField = value;
                    this.RaisePropertyChanged("Antecedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sugerencia {
            get {
                return this.SugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SugerenciaField, value) != true)) {
                    this.SugerenciaField = value;
                    this.RaisePropertyChanged("Sugerencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteEstatus", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class ComprobanteEstatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UltimaActualizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime UltimaActualizacion {
            get {
                return this.UltimaActualizacionField;
            }
            set {
                if ((this.UltimaActualizacionField.Equals(value) != true)) {
                    this.UltimaActualizacionField = value;
                    this.RaisePropertyChanged("UltimaActualizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionQR", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class InformacionQR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="ServiceReference1.Timbrado")]
    public interface Timbrado {
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudTimbraXML) of message SolicitudTimbraXML does not match the default value (TimbraXML)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXML", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLFallaServicioFault", Name="FallaServicio")]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaTimbraXML TimbraXML(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudTimbraXML request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudCancelaTimbrado) of message SolicitudCancelaTimbrado does not match the default value (CancelaTimbrado)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoFallaServicioFault", Name="FallaServicio")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoFallaSesionFault", Name="FallaSesion")]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaCancelaTimbrado CancelaTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudCancelaTimbrado request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudEstatusTimbrado) of message SolicitudEstatusTimbrado does not match the default value (EstatusTimbrado)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoFallaServicioFault", Name="FallaServicio")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoFallaSesionFault", Name="FallaSesion")]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaEstatusTimbrado EstatusTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudEstatusTimbrado request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudObtenerTimbrado) of message SolicitudObtenerTimbrado does not match the default value (ObtenerTimbrado)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoFallaServicioFault", Name="FallaServicio")]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaObtenerTimbrado ObtenerTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerTimbrado request);
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudObtenerQRTimbrado) of message SolicitudObtenerQRTimbrado does not match the default value (ObtenerQRTimbrado)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoFallaServicioFault", Name="FallaServicio")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.ServiceReference1.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoFallaValidacionFault", Name="FallaValidacion")]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaObtenerQRTimbrado ObtenerQRTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerQRTimbrado request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudTimbraXML", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudTimbraXML {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ComprobanteXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionID;
        
        public SolicitudTimbraXML() {
        }
        
        public SolicitudTimbraXML(FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ComprobanteXML, string RFC, string Token, long TransaccionID) {
            this.ComprobanteXML = ComprobanteXML;
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaTimbraXML", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaTimbraXML {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.AdvertenciasValidacion Advertencias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ComprobanteXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        public RespuestaTimbraXML() {
        }
        
        public RespuestaTimbraXML(FACT_ELECTRONICA_PDF_XML.ServiceReference1.AdvertenciasValidacion Advertencias, FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ComprobanteXML, long TransaccionID) {
            this.Advertencias = Advertencias;
            this.ComprobanteXML = ComprobanteXML;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudCancelaTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudCancelaTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public string UUID;
        
        public SolicitudCancelaTimbrado() {
        }
        
        public SolicitudCancelaTimbrado(string RFC, string Token, long TransaccionID, string UUID) {
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaCancelaTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaCancelaTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public bool Cancelada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaCancelaTimbrado() {
        }
        
        public RespuestaCancelaTimbrado(bool Cancelada, long TransaccionID) {
            this.Cancelada = Cancelada;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudEstatusTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudEstatusTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionOriginal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=4)]
        public string UUID;
        
        public SolicitudEstatusTimbrado() {
        }
        
        public SolicitudEstatusTimbrado(string RFC, string Token, long TransaccionID, long TransaccionOriginal, string UUID) {
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
            this.TransaccionOriginal = TransaccionOriginal;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaEstatusTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaEstatusTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteEstatus Estatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaEstatusTimbrado() {
        }
        
        public RespuestaEstatusTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteEstatus Estatus, long TransaccionID) {
            this.Estatus = Estatus;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudObtenerTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudObtenerTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionOriginal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=4)]
        public string UUID;
        
        public SolicitudObtenerTimbrado() {
        }
        
        public SolicitudObtenerTimbrado(string RFC, string Token, long TransaccionID, long TransaccionOriginal, string UUID) {
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
            this.TransaccionOriginal = TransaccionOriginal;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaObtenerTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaObtenerTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ComprobanteXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaObtenerTimbrado() {
        }
        
        public RespuestaObtenerTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ComprobanteXML, long TransaccionID) {
            this.ComprobanteXML = ComprobanteXML;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudObtenerQRTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudObtenerQRTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public string UUID;
        
        public SolicitudObtenerQRTimbrado() {
        }
        
        public SolicitudObtenerQRTimbrado(string RFC, string Token, long TransaccionID, string UUID) {
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaObtenerQRTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaObtenerQRTimbrado {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.InformacionQR QR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaObtenerQRTimbrado() {
        }
        
        public RespuestaObtenerQRTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.InformacionQR QR, long TransaccionID) {
            this.QR = QR;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimbradoChannel : FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimbradoClient : System.ServiceModel.ClientBase<FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado>, FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado {
        
        public TimbradoClient() {
        }
        
        public TimbradoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimbradoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimbradoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimbradoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaTimbraXML FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado.TimbraXML(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudTimbraXML request) {
            return base.Channel.TimbraXML(request);
        }
        
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.AdvertenciasValidacion TimbraXML(ref FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ComprobanteXML, string RFC, string Token, ref long TransaccionID) {
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudTimbraXML inValue = new FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudTimbraXML();
            inValue.ComprobanteXML = ComprobanteXML;
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaTimbraXML retVal = ((FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado)(this)).TimbraXML(inValue);
            ComprobanteXML = retVal.ComprobanteXML;
            TransaccionID = retVal.TransaccionID;
            return retVal.Advertencias;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaCancelaTimbrado FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado.CancelaTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudCancelaTimbrado request) {
            return base.Channel.CancelaTimbrado(request);
        }
        
        public bool CancelaTimbrado(string RFC, string Token, ref long TransaccionID, string UUID) {
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudCancelaTimbrado inValue = new FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudCancelaTimbrado();
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            inValue.UUID = UUID;
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaCancelaTimbrado retVal = ((FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado)(this)).CancelaTimbrado(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.Cancelada;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaEstatusTimbrado FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado.EstatusTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudEstatusTimbrado request) {
            return base.Channel.EstatusTimbrado(request);
        }
        
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteEstatus EstatusTimbrado(string RFC, string Token, ref long TransaccionID, long TransaccionOriginal, string UUID) {
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudEstatusTimbrado inValue = new FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudEstatusTimbrado();
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            inValue.TransaccionOriginal = TransaccionOriginal;
            inValue.UUID = UUID;
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaEstatusTimbrado retVal = ((FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado)(this)).EstatusTimbrado(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.Estatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaObtenerTimbrado FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado.ObtenerTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerTimbrado request) {
            return base.Channel.ObtenerTimbrado(request);
        }
        
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.ComprobanteXML ObtenerTimbrado(string RFC, string Token, ref long TransaccionID, long TransaccionOriginal, string UUID) {
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerTimbrado inValue = new FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerTimbrado();
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            inValue.TransaccionOriginal = TransaccionOriginal;
            inValue.UUID = UUID;
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaObtenerTimbrado retVal = ((FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado)(this)).ObtenerTimbrado(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.ComprobanteXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaObtenerQRTimbrado FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado.ObtenerQRTimbrado(FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerQRTimbrado request) {
            return base.Channel.ObtenerQRTimbrado(request);
        }
        
        public FACT_ELECTRONICA_PDF_XML.ServiceReference1.InformacionQR ObtenerQRTimbrado(string RFC, string Token, ref long TransaccionID, string UUID) {
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerQRTimbrado inValue = new FACT_ELECTRONICA_PDF_XML.ServiceReference1.SolicitudObtenerQRTimbrado();
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            inValue.UUID = UUID;
            FACT_ELECTRONICA_PDF_XML.ServiceReference1.RespuestaObtenerQRTimbrado retVal = ((FACT_ELECTRONICA_PDF_XML.ServiceReference1.Timbrado)(this)).ObtenerQRTimbrado(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.QR;
        }
    }
}
