//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACT_ELECTRONICA_PDF_XML.SrvInvoices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteXML", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class ComprobanteXML : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosXMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosXML {
            get {
                return this.DatosXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosXMLField, value) != true)) {
                    this.DatosXMLField = value;
                    this.RaisePropertyChanged("DatosXML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AdvertenciasValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI", ItemName="AdvertenciaValidacion")]
    [System.SerializableAttribute()]
    public class AdvertenciasValidacion : System.Collections.Generic.List<FACT_ELECTRONICA_PDF_XML.SrvInvoices.AdvertenciaValidacion> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvertenciaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class AdvertenciaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NodoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SugerenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nodo {
            get {
                return this.NodoField;
            }
            set {
                if ((object.ReferenceEquals(this.NodoField, value) != true)) {
                    this.NodoField = value;
                    this.RaisePropertyChanged("Nodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Antecedente {
            get {
                return this.AntecedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteField, value) != true)) {
                    this.AntecedenteField = value;
                    this.RaisePropertyChanged("Antecedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Sugerencia {
            get {
                return this.SugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SugerenciaField, value) != true)) {
                    this.SugerenciaField = value;
                    this.RaisePropertyChanged("Sugerencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaSesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaValidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AntecedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SugerenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Nodo {
            get {
                return this.NodoField;
            }
            set {
                if ((object.ReferenceEquals(this.NodoField, value) != true)) {
                    this.NodoField = value;
                    this.RaisePropertyChanged("Nodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Antecedente {
            get {
                return this.AntecedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.AntecedenteField, value) != true)) {
                    this.AntecedenteField = value;
                    this.RaisePropertyChanged("Antecedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sugerencia {
            get {
                return this.SugerenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SugerenciaField, value) != true)) {
                    this.SugerenciaField = value;
                    this.RaisePropertyChanged("Sugerencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="SrvInvoices.Comprobantes")]
    public interface Comprobantes {
        
        // CODEGEN: Generating message contract since the wrapper name (SolicitudSellaTimbraXML) of message SolicitudSellaTimbraXML does not match the default value (SellaTimbraXML)
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/ServicioFacturas/SellaTimbraXML", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Comprobantes/SellaTimbraXMLResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.SrvInvoices.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Comprobantes/SellaTimbraXMLFallaSesionFault", Name="FallaSesion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.SrvInvoices.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Comprobantes/SellaTimbraXMLFallaValidacionFault", Name="FallaValidacion")]
        [System.ServiceModel.FaultContractAttribute(typeof(FACT_ELECTRONICA_PDF_XML.SrvInvoices.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Comprobantes/SellaTimbraXMLFallaServicioFault", Name="FallaServicio")]
        FACT_ELECTRONICA_PDF_XML.SrvInvoices.RespuestaSellaTimbraXML SellaTimbraXML(FACT_ELECTRONICA_PDF_XML.SrvInvoices.SolicitudSellaTimbraXML request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudSellaTimbraXML", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudSellaTimbraXML {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public FACT_ELECTRONICA_PDF_XML.SrvInvoices.ComprobanteXML ComprobanteXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
        public long TransaccionID;
        
        public SolicitudSellaTimbraXML() {
        }
        
        public SolicitudSellaTimbraXML(FACT_ELECTRONICA_PDF_XML.SrvInvoices.ComprobanteXML ComprobanteXML, string RFC, string Token, long TransaccionID) {
            this.ComprobanteXML = ComprobanteXML;
            this.RFC = RFC;
            this.Token = Token;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaSellaTimbraXML", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaSellaTimbraXML {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public FACT_ELECTRONICA_PDF_XML.SrvInvoices.AdvertenciasValidacion Advertencias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public FACT_ELECTRONICA_PDF_XML.SrvInvoices.ComprobanteXML ComprobanteXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
        public long TransaccionID;
        
        public RespuestaSellaTimbraXML() {
        }
        
        public RespuestaSellaTimbraXML(FACT_ELECTRONICA_PDF_XML.SrvInvoices.AdvertenciasValidacion Advertencias, FACT_ELECTRONICA_PDF_XML.SrvInvoices.ComprobanteXML ComprobanteXML, long TransaccionID) {
            this.Advertencias = Advertencias;
            this.ComprobanteXML = ComprobanteXML;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComprobantesChannel : FACT_ELECTRONICA_PDF_XML.SrvInvoices.Comprobantes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComprobantesClient : System.ServiceModel.ClientBase<FACT_ELECTRONICA_PDF_XML.SrvInvoices.Comprobantes>, FACT_ELECTRONICA_PDF_XML.SrvInvoices.Comprobantes {
        
        public ComprobantesClient() {
        }
        
        public ComprobantesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComprobantesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobantesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComprobantesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FACT_ELECTRONICA_PDF_XML.SrvInvoices.RespuestaSellaTimbraXML FACT_ELECTRONICA_PDF_XML.SrvInvoices.Comprobantes.SellaTimbraXML(FACT_ELECTRONICA_PDF_XML.SrvInvoices.SolicitudSellaTimbraXML request) {
            return base.Channel.SellaTimbraXML(request);
        }
        
        public FACT_ELECTRONICA_PDF_XML.SrvInvoices.AdvertenciasValidacion SellaTimbraXML(ref FACT_ELECTRONICA_PDF_XML.SrvInvoices.ComprobanteXML ComprobanteXML, string RFC, string Token, ref long TransaccionID) {
            FACT_ELECTRONICA_PDF_XML.SrvInvoices.SolicitudSellaTimbraXML inValue = new FACT_ELECTRONICA_PDF_XML.SrvInvoices.SolicitudSellaTimbraXML();
            inValue.ComprobanteXML = ComprobanteXML;
            inValue.RFC = RFC;
            inValue.Token = Token;
            inValue.TransaccionID = TransaccionID;
            FACT_ELECTRONICA_PDF_XML.SrvInvoices.RespuestaSellaTimbraXML retVal = ((FACT_ELECTRONICA_PDF_XML.SrvInvoices.Comprobantes)(this)).SellaTimbraXML(inValue);
            ComprobanteXML = retVal.ComprobanteXML;
            TransaccionID = retVal.TransaccionID;
            return retVal.Advertencias;
        }
    }
}
